---
title: "Untitled"
author: "Ashton Pallottini"
date: "February 24, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stringr)
```


```{r}
nd.data <- read.csv("ND_Data.csv", header = T, na.strings = "", stringsAsFactors = F)
```

```{r}
nd.data1 <- as.tibble(nd.data[1:7536, c(1:5,10,11)])
colnames(nd.data1) <- c("year", "type", "iso", "country", "occurrence", "affected", "damage")
```

```{r}
nd.data1

nd.data2 <- nd.data1 %>% spread(key = type, value = occurrence) %>% arrange(country)

nd.data2[is.na(nd.data2)] <- 0

nd.data2
```

```{r}
nd.data2[6700:7476,]
```


```{r}
length(unique(nd.data2$country))

data_matrix <- matrix(nrow = 13607, ncol = 11)
data.tib <- as.tibble(data_matrix)
colnames(data.tib) <- colnames(nd.data2)

year <- 1961
j <- 1
i <- 1
while(i <= 13607){
  if(nd.data2[j, 1] == year){
    if(nd.data2[j,1] == nd.data2[j+1,1] & nd.data2[j+1,1] == nd.data2[j+2,1] & nd.data2[j+2,1] ==  nd.data2[j+3,1]){
      data.tib[i,] <- nd.data2[j,]
      data.tib[[i,4]] <- as.integer(nd.data2[j,4]) + as.integer(nd.data2[j+1,4]) + as.integer(nd.data2[j+2,4]) + as.integer(nd.data2[j+3,4])
      data.tib[[i,5]] <- as.integer(nd.data2[j,5]) + as.integer(nd.data2[j+1,5]) + as.integer(nd.data2[j+2,5]) + as.integer(nd.data2[j+3,5])
      i <- i + 1
      j <- j + 4
      year <- year + 1
    }
    else if(nd.data2[j,1] == nd.data2[j+1,1] & nd.data2[j+1,1] == nd.data2[j+2,1]){
      data.tib[i,] <- nd.data2[j,]
      data.tib[[i,4]] <- as.integer(nd.data2[j,4]) + as.integer(nd.data2[j+1,4]) + as.integer(nd.data2[j+2,4])
      data.tib[[i,5]] <- as.integer(nd.data2[j,5]) + as.integer(nd.data2[j+1,5]) + as.integer(nd.data2[j+2,5])
      i <- i + 1
      j <- j + 3
      year <- year + 1
    }
    else if(nd.data2[j,1] == nd.data2[j+1,1]){
      data.tib[i,] <- nd.data2[j,]
      data.tib[[i,4]] <- as.integer(nd.data2[j,4]) + as.integer(nd.data2[j+1,4])
      data.tib[[i,5]] <- as.integer(nd.data2[j,5]) + as.integer(nd.data2[j+1,5])
      i <- i + 1
      j <- j + 2
      year <- year + 1
    }
    else{
      data.tib[i,] <- nd.data2[j,]
      j <- j + 1
      i <- i + 1
      year <- year + 1
    }
  }
  else{
    data.tib[i,] <- c(0,0,0,0,0,0,0,0,0,0,0)
    year <- year + 1
    i <- i + 1
  }
  if(year == 2017){
    year <- 1961
  }
}
```

```{r}
data.tib[13200:13607,]
```


```{r}
clean.data <- as.data.frame(data.tib)
write.csv(clean.data, "clean.damages.data.csv")
```

